
package fahrtenbuch;

import java.util.ArrayList;

/**
 *
 * @author Michael und Daniel und Sophie und Jahed
 */
public class MainView extends javax.swing.JFrame {
    
 
    private String [] driverModel;
    private String[] carModel;
    
    //Creates new form FahrtenbuchFrame
    
    public MainView() {
        initComponents();
    }
    
    public MainView(ArrayList<String> driverName, ArrayList<String> carName) { 
        driverModel = new String[driverName.size()];
        carModel = new String[carName.size()];
        
        int count = 0;
        int count2= 0;
        
        for(String name : driverName)
        {
            driverModel[count] = name;
            count++;
        }
          for(String model : carName)
        {
            carModel[count2] = model;
            count2++;
        }
                
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainViewLabel = new javax.swing.JPanel();
        DriverLabel = new javax.swing.JLabel();
        StartLabel = new javax.swing.JLabel();
        CarLabel = new javax.swing.JLabel();
        EndLabel = new javax.swing.JLabel();
        kmLabel = new javax.swing.JLabel();
        ReasonLabel = new javax.swing.JLabel();
        ReasonField = new javax.swing.JTextField();
        CarComboBox = new javax.swing.JComboBox<>();
        kmField = new javax.swing.JTextField();
        DriverComboBox = new javax.swing.JComboBox<>();
        CancelButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DriverLabel.setText("Fahrer");

        StartLabel.setText("Starrt");

        CarLabel.setText("Fahrzeug");

        EndLabel.setText("Ende");

        kmLabel.setText("Km");

        ReasonLabel.setText("Grund");

        ReasonField.setText("jTextField1");

        CarComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(carModel));
        CarComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarComboBoxActionPerformed(evt);
            }
        });

        kmField.setText("jTextField1");

        DriverComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(driverModel));

        CancelButton.setText("Abbrechen");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Speichern");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainViewLabelLayout = new javax.swing.GroupLayout(MainViewLabel);
        MainViewLabel.setLayout(MainViewLabelLayout);
        MainViewLabelLayout.setHorizontalGroup(
            MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainViewLabelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainViewLabelLayout.createSequentialGroup()
                        .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DriverLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReasonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kmLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(StartLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DriverComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CarComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(kmField)
                            .addComponent(ReasonField, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(MainViewLabelLayout.createSequentialGroup()
                        .addComponent(SaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(CancelButton)))
                .addGap(58, 58, 58))
        );
        MainViewLabelLayout.setVerticalGroup(
            MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainViewLabelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DriverLabel)
                    .addComponent(DriverComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarLabel)
                    .addComponent(CarComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(StartLabel)
                .addGap(15, 15, 15)
                .addComponent(EndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kmLabel)
                    .addComponent(kmField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReasonLabel)
                    .addComponent(ReasonField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(MainViewLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelButton)
                    .addComponent(SaveButton))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainViewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(MainViewLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
     //DefaultTableModel model =(DefaultTableModel) MainTable.getModel();
    // MainTable.getModel();
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void CarComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox<String> CarComboBox;
    private javax.swing.JLabel CarLabel;
    private javax.swing.JComboBox<String> DriverComboBox;
    private javax.swing.JLabel DriverLabel;
    private javax.swing.JLabel EndLabel;
    private javax.swing.JPanel MainViewLabel;
    private javax.swing.JTextField ReasonField;
    private javax.swing.JLabel ReasonLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel StartLabel;
    private javax.swing.JTextField kmField;
    private javax.swing.JLabel kmLabel;
    // End of variables declaration//GEN-END:variables
}
